// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqatjn08sm-Y9lgUC1LJOxsz5FJIBN-FU',
    appId: '1:1070733316751:web:6a1c4f511d8cc9aa37d6fa',
    messagingSenderId: '1070733316751',
    projectId: 'tastytakeoutimagestoreage',
    authDomain: 'tastytakeoutimagestoreage.firebaseapp.com',
    storageBucket: 'tastytakeoutimagestoreage.appspot.com',
    measurementId: 'G-0BB9ZMM8VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIsP1dGKPNK2aogFJkovz6eBmosmX6EU',
    appId: '1:1070733316751:android:61e49f47517d9ee737d6fa',
    messagingSenderId: '1070733316751',
    projectId: 'tastytakeoutimagestoreage',
    storageBucket: 'tastytakeoutimagestoreage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBhVnlxlP3DxnVn9GJtbv_Jb1sSToMlsU',
    appId: '1:1070733316751:ios:ec21371586a4e60637d6fa',
    messagingSenderId: '1070733316751',
    projectId: 'tastytakeoutimagestoreage',
    storageBucket: 'tastytakeoutimagestoreage.appspot.com',
    iosBundleId: 'com.example.tastytakeoutAdminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBhVnlxlP3DxnVn9GJtbv_Jb1sSToMlsU',
    appId: '1:1070733316751:ios:ab47b06fe93e9fef37d6fa',
    messagingSenderId: '1070733316751',
    projectId: 'tastytakeoutimagestoreage',
    storageBucket: 'tastytakeoutimagestoreage.appspot.com',
    iosBundleId: 'com.example.tastytakeoutAdminWeb.RunnerTests',
  );
}
